// AUTO-GENERATED by scripts/apply_brand.py — do not edit by hand.
// Source of truth: brand.config.json

export const BRAND = {
  name: { zh: "麦途智造", en: "MAITU Smart Manufacturing" },
  fullName: { zh: "苏州麦途", en: "Suzhou Maitou" },
  shortName: { zh: "麦途智造", en: "MAITU" },
  description: { zh: "麦途智造 · 面向制造企业的 AI 工作平台", en: "MAITU Smart Manufacturing · AI workspace for manufacturers" },
  logo: {
    mark: "/brand/mark-512.png",
    wordmarkLight: "/brand/wordmark-light.png",
    wordmarkDark: "/brand/wordmark-dark.png",
    favicon: "/brand/favicon.png",
    appleTouchIcon: "/brand/apple-touch-icon.png",
    pwa192: "/brand/pwa-192.png",
    pwa512: "/brand/pwa-512.png",
  },
  color: {
    brand: "#FE0000",
    accent: "#E5484D",
  },
  links: {
    // Empty string hides the "project URL" entry in the account menu.
    projectRepo: "",
  },
} as const;

/** Pick the brand name for the active UI language. */
export function brandName(lang: string | undefined): string {
  return lang?.toLowerCase().startsWith("zh") ? BRAND.name.zh : BRAND.name.en;
}

/** Wordmark for the current theme. */
export function wordmark(isDark: boolean): string {
  return isDark ? BRAND.logo.wordmarkDark : BRAND.logo.wordmarkLight;
}
